### ISSUE TITLE
Passing non-US-ASCII string to Atom::Entry#content= causes an error.

### ISSUE THREAD

**Issue by rnanba** [lyokato/ruby-atomutil#3]
I'm using atomutil 0.1.4 with ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]. The following code results in an error. 

```
# coding: utf-8
require 'atomutil'
entry = Atom::Entry.new
entry.content = "こんにちは"
```

```
Traceback (most recent call last):
	9: from /home/rna/tmp/atom-utf-8.rb:4:in `<main>'
	8: from /var/lib/gems/2.5.0/gems/atomutil-0.1.4/lib/atomutil.rb:1046:in `content='
	7: from /var/lib/gems/2.5.0/gems/atomutil-0.1.4/lib/atomutil.rb:236:in `new'
	6: from /var/lib/gems/2.5.0/gems/atomutil-0.1.4/lib/atomutil.rb:236:in `new'
	5: from /var/lib/gems/2.5.0/gems/atomutil-0.1.4/lib/atomutil.rb:750:in `initialize'
	4: from /var/lib/gems/2.5.0/gems/atomutil-0.1.4/lib/atomutil.rb:455:in `initialize'
	3: from /var/lib/gems/2.5.0/gems/atomutil-0.1.4/lib/atomutil.rb:455:in `each'
	2: from /var/lib/gems/2.5.0/gems/atomutil-0.1.4/lib/atomutil.rb:457:in `block in initialize'
	1: from /var/lib/gems/2.5.0/gems/atomutil-0.1.4/lib/atomutil.rb:757:in `body='
/var/lib/gems/2.5.0/gems/atomutil-0.1.4/lib/atomutil.rb:757:in `=~': incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string) (Encoding::CompatibilityError)
```

To avoid the error above, I passed an ASCII-8BIT string, but an error occurred in another place.

```
# coding: utf-8
require 'atomutil'
entry = Atom::Entry.new
entry.content = "こんにちは".force_encoding("ASCII-8BIT")
```

```
Traceback (most recent call last):
	7: from /home/rna/tmp/atom-ascii-8bit.rb:4:in `<main>'
	6: from /var/lib/gems/2.5.0/gems/atomutil-0.1.4/lib/atomutil.rb:1048:in `content='
	5: from /var/lib/gems/2.5.0/gems/atomutil-0.1.4/lib/atomutil.rb:501:in `set'
	4: from /var/lib/gems/2.5.0/gems/atomutil-0.1.4/lib/atomutil.rb:526:in `add'
	3: from /usr/lib/ruby/2.5.0/rexml/element.rb:453:in `text'
	2: from /usr/lib/ruby/2.5.0/rexml/text.rb:253:in `value'
	1: from /usr/lib/ruby/2.5.0/rexml/text.rb:396:in `unnormalize'
/usr/lib/ruby/2.5.0/rexml/text.rb:396:in `gsub': incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string) (Encoding::CompatibilityError)
```

How can I set non-ASCII text to content?

**Comment by lyokato** [comment]
now it works with this test.

https://github.com/lyokato/ruby-atomutil/pull/4/files#diff-7f15042bd19550373c4cc71dbbf2c8bbR35

Thanks.
